# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'overview.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import graphic_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1544, 836)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"QFrame#frame\n"
"{\n"
"background-image: url(:/background/Overview.svg);\n"
"background-color: rgb(192, 192, 192);\n"
"background-repeat: no-repeat;\n"
"background-attachment: fixed;\n"
"background-clip: padding;\n"
"background-position:left top;\n"
"}")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.bICFCConeStopSensor = QPushButton(self.frame)
        self.bICFCConeStopSensor.setObjectName(u"bICFCConeStopSensor")
        self.bICFCConeStopSensor.setGeometry(QRect(735, 120, 35, 28))
        icon = QIcon()
        icon.addFile(u":/buttonImage/greenButton.png", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u":/buttonImage/redButton.png", QSize(), QIcon.Disabled, QIcon.Off)
        icon.addFile(u":/buttonImage/redButton.png", QSize(), QIcon.Disabled, QIcon.On)
        self.bICFCConeStopSensor.setIcon(icon)
        self.bICFCConeStopSensor.setIconSize(QSize(20, 20))
        self.bICFCConeStopSensor.setFlat(True)
        self.bIRetA_Middle = QPushButton(self.frame)
        self.bIRetA_Middle.setObjectName(u"bIRetA_Middle")
        self.bIRetA_Middle.setGeometry(QRect(272, 264, 24, 23))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.bIRetA_Middle.setFont(font)
        self.bIRetA_Middle.setFocusPolicy(Qt.NoFocus)
        self.bIRetA_Middle.setToolTipDuration(4)
        icon1 = QIcon()
        icon1.addFile(u":/magneticSwitch/greenSquareButton.png", QSize(), QIcon.Normal, QIcon.Off)
        icon1.addFile(u":/magneticSwitch/redSquareButton.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.bIRetA_Middle.setIcon(icon1)
        self.bIRetA_Middle.setIconSize(QSize(12, 12))
        self.bIRetA_Middle.setFlat(True)
        self.bQRetB_WeightOk = QPushButton(self.frame)
        self.bQRetB_WeightOk.setObjectName(u"bQRetB_WeightOk")
        self.bQRetB_WeightOk.setGeometry(QRect(386, 427, 35, 28))
        self.bQRetB_WeightOk.setIcon(icon)
        self.bQRetB_WeightOk.setIconSize(QSize(20, 20))
        self.bQRetB_WeightOk.setFlat(True)
        self.bIRetB_End = QPushButton(self.frame)
        self.bIRetB_End.setObjectName(u"bIRetB_End")
        self.bIRetB_End.setGeometry(QRect(575, 206, 24, 23))
        self.bIRetB_End.setFont(font)
        self.bIRetB_End.setFocusPolicy(Qt.NoFocus)
        self.bIRetB_End.setToolTipDuration(4)
        self.bIRetB_End.setIcon(icon1)
        self.bIRetB_End.setIconSize(QSize(12, 12))
        self.bIRetB_End.setFlat(True)
        self.bQConeFeedingPiston = QPushButton(self.frame)
        self.bQConeFeedingPiston.setObjectName(u"bQConeFeedingPiston")
        self.bQConeFeedingPiston.setGeometry(QRect(777, 60, 23, 41))
        icon2 = QIcon()
        icon2.addFile(u":/pistonColor/pistionV.png", QSize(), QIcon.Normal, QIcon.Off)
        icon2.addFile(u":/pistonColor/pistionTV.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.bQConeFeedingPiston.setIcon(icon2)
        self.bQConeFeedingPiston.setIconSize(QSize(200, 200))
        self.bQConeFeedingPiston.setAutoRepeatDelay(300)
        self.bQConeFeedingPiston.setFlat(True)
        self.layoutWidget = QWidget(self.frame)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(395, 119, 205, 28))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setSpacing(25)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.bIRetB_ConeDetection1 = QPushButton(self.layoutWidget)
        self.bIRetB_ConeDetection1.setObjectName(u"bIRetB_ConeDetection1")
        self.bIRetB_ConeDetection1.setIcon(icon)
        self.bIRetB_ConeDetection1.setIconSize(QSize(20, 20))
        self.bIRetB_ConeDetection1.setFlat(True)

        self.horizontalLayout_2.addWidget(self.bIRetB_ConeDetection1)

        self.bIRetB_ConeDetection2 = QPushButton(self.layoutWidget)
        self.bIRetB_ConeDetection2.setObjectName(u"bIRetB_ConeDetection2")
        self.bIRetB_ConeDetection2.setIcon(icon)
        self.bIRetB_ConeDetection2.setIconSize(QSize(20, 20))
        self.bIRetB_ConeDetection2.setFlat(True)

        self.horizontalLayout_2.addWidget(self.bIRetB_ConeDetection2)

        self.bIRetB_ConeDetection3 = QPushButton(self.layoutWidget)
        self.bIRetB_ConeDetection3.setObjectName(u"bIRetB_ConeDetection3")
        self.bIRetB_ConeDetection3.setIcon(icon)
        self.bIRetB_ConeDetection3.setIconSize(QSize(20, 20))
        self.bIRetB_ConeDetection3.setFlat(True)

        self.horizontalLayout_2.addWidget(self.bIRetB_ConeDetection3)

        self.bIRetB_ConeDetection4 = QPushButton(self.layoutWidget)
        self.bIRetB_ConeDetection4.setObjectName(u"bIRetB_ConeDetection4")
        self.bIRetB_ConeDetection4.setIcon(icon)
        self.bIRetB_ConeDetection4.setIconSize(QSize(20, 20))
        self.bIRetB_ConeDetection4.setFlat(True)

        self.horizontalLayout_2.addWidget(self.bIRetB_ConeDetection4)

        self.bQRetAForward = QPushButton(self.frame)
        self.bQRetAForward.setObjectName(u"bQRetAForward")
        self.bQRetAForward.setGeometry(QRect(135, 245, 91, 61))
        icon3 = QIcon()
        icon3.addFile(u":/arrowTriangle/uparrow.png", QSize(), QIcon.Normal, QIcon.Off)
        icon3.addFile(u":/arrowTriangle/downarrow.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.bQRetAForward.setIcon(icon3)
        self.bQRetAForward.setIconSize(QSize(70, 70))
        self.bQRetAForward.setCheckable(False)
        self.bQRetAForward.setAutoRepeat(False)
        self.bQRetAForward.setFlat(True)
        self.bQFeedingConveyorMotor = QPushButton(self.frame)
        self.bQFeedingConveyorMotor.setObjectName(u"bQFeedingConveyorMotor")
        self.bQFeedingConveyorMotor.setGeometry(QRect(33, 120, 21, 78))
        self.bQFeedingConveyorMotor.setFont(font)
        self.bQFeedingConveyorMotor.setFocusPolicy(Qt.NoFocus)
        self.bQFeedingConveyorMotor.setToolTipDuration(4)
        icon4 = QIcon()
        icon4.addFile(u":/recSwitch/greenRec.png", QSize(), QIcon.Normal, QIcon.Off)
        icon4.addFile(u":/recSwitch/redRec.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.bQFeedingConveyorMotor.setIcon(icon4)
        self.bQFeedingConveyorMotor.setIconSize(QSize(100, 100))
        self.bQFeedingConveyorMotor.setFlat(True)
        self.layoutWidget_2 = QWidget(self.frame)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(87, 120, 205, 28))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.bIRetA_ConeDetection1 = QPushButton(self.layoutWidget_2)
        self.bIRetA_ConeDetection1.setObjectName(u"bIRetA_ConeDetection1")
        self.bIRetA_ConeDetection1.setAcceptDrops(False)
        self.bIRetA_ConeDetection1.setIcon(icon)
        self.bIRetA_ConeDetection1.setIconSize(QSize(20, 20))
        self.bIRetA_ConeDetection1.setFlat(True)

        self.horizontalLayout.addWidget(self.bIRetA_ConeDetection1)

        self.bIRetA_ConeDetection2 = QPushButton(self.layoutWidget_2)
        self.bIRetA_ConeDetection2.setObjectName(u"bIRetA_ConeDetection2")
        self.bIRetA_ConeDetection2.setIcon(icon)
        self.bIRetA_ConeDetection2.setIconSize(QSize(20, 20))
        self.bIRetA_ConeDetection2.setFlat(True)

        self.horizontalLayout.addWidget(self.bIRetA_ConeDetection2)

        self.bIRetA_ConeDetection3 = QPushButton(self.layoutWidget_2)
        self.bIRetA_ConeDetection3.setObjectName(u"bIRetA_ConeDetection3")
        self.bIRetA_ConeDetection3.setIcon(icon)
        self.bIRetA_ConeDetection3.setIconSize(QSize(20, 20))
        self.bIRetA_ConeDetection3.setFlat(True)

        self.horizontalLayout.addWidget(self.bIRetA_ConeDetection3)

        self.bIRetA_ConeDetection4 = QPushButton(self.layoutWidget_2)
        self.bIRetA_ConeDetection4.setObjectName(u"bIRetA_ConeDetection4")
        self.bIRetA_ConeDetection4.setIcon(icon)
        self.bIRetA_ConeDetection4.setIconSize(QSize(20, 20))
        self.bIRetA_ConeDetection4.setFlat(True)

        self.horizontalLayout.addWidget(self.bIRetA_ConeDetection4)

        self.bIRetA_Home = QPushButton(self.frame)
        self.bIRetA_Home.setObjectName(u"bIRetA_Home")
        self.bIRetA_Home.setGeometry(QRect(275, 346, 20, 20))
        self.bIRetA_Home.setFont(font)
        self.bIRetA_Home.setFocusPolicy(Qt.NoFocus)
        self.bIRetA_Home.setToolTipDuration(4)
        self.bIRetA_Home.setIcon(icon1)
        self.bIRetA_Home.setIconSize(QSize(12, 12))
        self.bIRetA_Home.setFlat(True)
        self.bQRetBForward = QPushButton(self.frame)
        self.bQRetBForward.setObjectName(u"bQRetBForward")
        self.bQRetBForward.setGeometry(QRect(445, 245, 91, 61))
        self.bQRetBForward.setIcon(icon3)
        self.bQRetBForward.setIconSize(QSize(70, 70))
        self.bQRetBForward.setCheckable(False)
        self.bQRetBForward.setAutoRepeat(False)
        self.bQRetBForward.setFlat(True)
        self.bQRetA_WeightOk = QPushButton(self.frame)
        self.bQRetA_WeightOk.setObjectName(u"bQRetA_WeightOk")
        self.bQRetA_WeightOk.setGeometry(QRect(95, 427, 35, 28))
        self.bQRetA_WeightOk.setIcon(icon)
        self.bQRetA_WeightOk.setIconSize(QSize(20, 20))
        self.bQRetA_WeightOk.setFlat(True)
        self.bIConeFeedingPistonEnd = QPushButton(self.frame)
        self.bIConeFeedingPistonEnd.setObjectName(u"bIConeFeedingPistonEnd")
        self.bIConeFeedingPistonEnd.setGeometry(QRect(776, 102, 25, 17))
        self.bIConeFeedingPistonEnd.setFont(font)
        self.bIConeFeedingPistonEnd.setFocusPolicy(Qt.NoFocus)
        self.bIConeFeedingPistonEnd.setToolTipDuration(4)
        self.bIConeFeedingPistonEnd.setIcon(icon1)
        self.bIConeFeedingPistonEnd.setIconSize(QSize(100, 100))
        self.bIConeFeedingPistonEnd.setFlat(True)
        self.bIRetA_End = QPushButton(self.frame)
        self.bIRetA_End.setObjectName(u"bIRetA_End")
        self.bIRetA_End.setGeometry(QRect(273, 205, 24, 23))
        self.bIRetA_End.setFont(font)
        self.bIRetA_End.setFocusPolicy(Qt.NoFocus)
        self.bIRetA_End.setToolTipDuration(4)
        self.bIRetA_End.setIcon(icon1)
        self.bIRetA_End.setIconSize(QSize(12, 12))
        self.bIRetA_End.setFlat(True)
        self.bIRetA_ConeCrossLimitSwitch = QPushButton(self.frame)
        self.bIRetA_ConeCrossLimitSwitch.setObjectName(u"bIRetA_ConeCrossLimitSwitch")
        self.bIRetA_ConeCrossLimitSwitch.setGeometry(QRect(345, 116, 16, 28))
        self.bIRetA_ConeCrossLimitSwitch.setFont(font)
        self.bIRetA_ConeCrossLimitSwitch.setFocusPolicy(Qt.NoFocus)
        self.bIRetA_ConeCrossLimitSwitch.setToolTipDuration(4)
        self.bIRetA_ConeCrossLimitSwitch.setIcon(icon4)
        self.bIRetA_ConeCrossLimitSwitch.setIconSize(QSize(20, 20))
        self.bIRetA_ConeCrossLimitSwitch.setFlat(True)
        self.bIRetB_Middle = QPushButton(self.frame)
        self.bIRetB_Middle.setObjectName(u"bIRetB_Middle")
        self.bIRetB_Middle.setGeometry(QRect(573, 266, 24, 23))
        self.bIRetB_Middle.setFont(font)
        self.bIRetB_Middle.setFocusPolicy(Qt.NoFocus)
        self.bIRetB_Middle.setToolTipDuration(4)
        self.bIRetB_Middle.setIcon(icon1)
        self.bIRetB_Middle.setIconSize(QSize(12, 12))
        self.bIRetB_Middle.setFlat(True)
        self.bIRetB_ConeCrossLimitSwitch = QPushButton(self.frame)
        self.bIRetB_ConeCrossLimitSwitch.setObjectName(u"bIRetB_ConeCrossLimitSwitch")
        self.bIRetB_ConeCrossLimitSwitch.setGeometry(QRect(605, 118, 16, 28))
        self.bIRetB_ConeCrossLimitSwitch.setFont(font)
        self.bIRetB_ConeCrossLimitSwitch.setFocusPolicy(Qt.NoFocus)
        self.bIRetB_ConeCrossLimitSwitch.setToolTipDuration(4)
        self.bIRetB_ConeCrossLimitSwitch.setIcon(icon4)
        self.bIRetB_ConeCrossLimitSwitch.setIconSize(QSize(20, 20))
        self.bIRetB_ConeCrossLimitSwitch.setFlat(True)
        self.Ret_A_Wt = QLabel(self.frame)
        self.Ret_A_Wt.setObjectName(u"Ret_A_Wt")
        self.Ret_A_Wt.setGeometry(QRect(135, 417, 131, 51))
        self.Ret_A_Wt.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid black")
        self.Ret_A_Wt.setFrameShape(QFrame.Box)
        self.Ret_A_Wt.setFrameShadow(QFrame.Raised)
        self.Ret_A_Wt.setLineWidth(2)
        self.Ret_A_Wt.setAlignment(Qt.AlignCenter)
        self.Ret_B_Wt = QLabel(self.frame)
        self.Ret_B_Wt.setObjectName(u"Ret_B_Wt")
        self.Ret_B_Wt.setGeometry(QRect(426, 417, 131, 51))
        self.Ret_B_Wt.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid black")
        self.Ret_B_Wt.setFrameShape(QFrame.Box)
        self.Ret_B_Wt.setFrameShadow(QFrame.Raised)
        self.Ret_B_Wt.setLineWidth(2)
        self.Ret_B_Wt.setAlignment(Qt.AlignCenter)
        self.bIConeFeedingPistonHome = QPushButton(self.frame)
        self.bIConeFeedingPistonHome.setObjectName(u"bIConeFeedingPistonHome")
        self.bIConeFeedingPistonHome.setGeometry(QRect(776, 42, 25, 19))
        self.bIConeFeedingPistonHome.setFont(font)
        self.bIConeFeedingPistonHome.setFocusPolicy(Qt.NoFocus)
        self.bIConeFeedingPistonHome.setToolTipDuration(4)
        self.bIConeFeedingPistonHome.setIcon(icon1)
        self.bIConeFeedingPistonHome.setIconSize(QSize(100, 100))
        self.bIConeFeedingPistonHome.setFlat(True)
        self.bIRetB_Home = QPushButton(self.frame)
        self.bIRetB_Home.setObjectName(u"bIRetB_Home")
        self.bIRetB_Home.setGeometry(QRect(574, 347, 20, 20))
        self.bIRetB_Home.setFont(font)
        self.bIRetB_Home.setFocusPolicy(Qt.NoFocus)
        self.bIRetB_Home.setToolTipDuration(4)
        self.bIRetB_Home.setIcon(icon1)
        self.bIRetB_Home.setIconSize(QSize(12, 12))
        self.bIRetB_Home.setFlat(True)
        self.bIForwardPistonEnd = QPushButton(self.frame)
        self.bIForwardPistonEnd.setObjectName(u"bIForwardPistonEnd")
        self.bIForwardPistonEnd.setGeometry(QRect(745, 224, 19, 26))
        self.bIForwardPistonEnd.setFont(font)
        self.bIForwardPistonEnd.setFocusPolicy(Qt.NoFocus)
        self.bIForwardPistonEnd.setToolTipDuration(4)
        self.bIForwardPistonEnd.setIcon(icon1)
        self.bIForwardPistonEnd.setIconSize(QSize(100, 100))
        self.bIForwardPistonEnd.setFlat(True)
        self.bIForwardPistonHome = QPushButton(self.frame)
        self.bIForwardPistonHome.setObjectName(u"bIForwardPistonHome")
        self.bIForwardPistonHome.setGeometry(QRect(685, 224, 18, 25))
        self.bIForwardPistonHome.setFont(font)
        self.bIForwardPistonHome.setFocusPolicy(Qt.NoFocus)
        self.bIForwardPistonHome.setToolTipDuration(4)
        self.bIForwardPistonHome.setIcon(icon1)
        self.bIForwardPistonHome.setIconSize(QSize(100, 100))
        self.bIForwardPistonHome.setFlat(True)
        self.bQForwardPiston = QPushButton(self.frame)
        self.bQForwardPiston.setObjectName(u"bQForwardPiston")
        self.bQForwardPiston.setGeometry(QRect(704, 225, 40, 25))
        icon5 = QIcon()
        icon5.addFile(u":/pistonColor/pistionV1.png", QSize(), QIcon.Normal, QIcon.Off)
        icon5.addFile(u":/pistonColor/pistionTV.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.bQForwardPiston.setIcon(icon5)
        self.bQForwardPiston.setIconSize(QSize(200, 200))
        self.bQForwardPiston.setFlat(True)
        self.bIConeTiltingPistonHome = QPushButton(self.frame)
        self.bIConeTiltingPistonHome.setObjectName(u"bIConeTiltingPistonHome")
        self.bIConeTiltingPistonHome.setGeometry(QRect(767, 198, 38, 18))
        self.bIConeTiltingPistonHome.setFont(font)
        self.bIConeTiltingPistonHome.setFocusPolicy(Qt.NoFocus)
        self.bIConeTiltingPistonHome.setToolTipDuration(4)
        self.bIConeTiltingPistonHome.setIcon(icon1)
        self.bIConeTiltingPistonHome.setIconSize(QSize(100, 100))
        self.bIConeTiltingPistonHome.setFlat(True)
        self.bQConeTiltingPistonForward = QPushButton(self.frame)
        self.bQConeTiltingPistonForward.setObjectName(u"bQConeTiltingPistonForward")
        self.bQConeTiltingPistonForward.setGeometry(QRect(768, 216, 37, 40))
        self.bQConeTiltingPistonForward.setIcon(icon5)
        self.bQConeTiltingPistonForward.setIconSize(QSize(200, 200))
        self.bQConeTiltingPistonForward.setFlat(True)
        self.bIConeTiltingPistonEnd = QPushButton(self.frame)
        self.bIConeTiltingPistonEnd.setObjectName(u"bIConeTiltingPistonEnd")
        self.bIConeTiltingPistonEnd.setGeometry(QRect(767, 256, 39, 19))
        self.bIConeTiltingPistonEnd.setFont(font)
        self.bIConeTiltingPistonEnd.setFocusPolicy(Qt.NoFocus)
        self.bIConeTiltingPistonEnd.setToolTipDuration(4)
        self.bIConeTiltingPistonEnd.setIcon(icon1)
        self.bIConeTiltingPistonEnd.setIconSize(QSize(100, 100))
        self.bIConeTiltingPistonEnd.setFlat(True)
        self.layoutWidget_5 = QWidget(self.frame)
        self.layoutWidget_5.setObjectName(u"layoutWidget_5")
        self.layoutWidget_5.setGeometry(QRect(826, 198, 241, 28))
        self.horizontalLayout_5 = QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setSpacing(35)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.bITransferConveyorHome = QPushButton(self.layoutWidget_5)
        self.bITransferConveyorHome.setObjectName(u"bITransferConveyorHome")
        self.bITransferConveyorHome.setIcon(icon)
        self.bITransferConveyorHome.setIconSize(QSize(20, 20))
        self.bITransferConveyorHome.setFlat(True)

        self.horizontalLayout_5.addWidget(self.bITransferConveyorHome)

        self.bITransferConveyorMiddle = QPushButton(self.layoutWidget_5)
        self.bITransferConveyorMiddle.setObjectName(u"bITransferConveyorMiddle")
        self.bITransferConveyorMiddle.setIcon(icon)
        self.bITransferConveyorMiddle.setIconSize(QSize(20, 20))
        self.bITransferConveyorMiddle.setFlat(True)

        self.horizontalLayout_5.addWidget(self.bITransferConveyorMiddle)

        self.bITransferConveyorEnd = QPushButton(self.layoutWidget_5)
        self.bITransferConveyorEnd.setObjectName(u"bITransferConveyorEnd")
        self.bITransferConveyorEnd.setIcon(icon)
        self.bITransferConveyorEnd.setIconSize(QSize(20, 20))
        self.bITransferConveyorEnd.setFlat(True)

        self.horizontalLayout_5.addWidget(self.bITransferConveyorEnd)

        self.bITransferConveyorExit = QPushButton(self.layoutWidget_5)
        self.bITransferConveyorExit.setObjectName(u"bITransferConveyorExit")
        self.bITransferConveyorExit.setIcon(icon)
        self.bITransferConveyorExit.setIconSize(QSize(20, 20))
        self.bITransferConveyorExit.setFlat(True)

        self.horizontalLayout_5.addWidget(self.bITransferConveyorExit)

        self.layoutWidget_6 = QWidget(self.frame)
        self.layoutWidget_6.setObjectName(u"layoutWidget_6")
        self.layoutWidget_6.setGeometry(QRect(1088, 198, 171, 30))
        self.horizontalLayout_6 = QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.bIWrappingConveyorHome = QPushButton(self.layoutWidget_6)
        self.bIWrappingConveyorHome.setObjectName(u"bIWrappingConveyorHome")
        self.bIWrappingConveyorHome.setIcon(icon)
        self.bIWrappingConveyorHome.setIconSize(QSize(20, 20))
        self.bIWrappingConveyorHome.setFlat(True)

        self.horizontalLayout_6.addWidget(self.bIWrappingConveyorHome)

        self.bIWrappingConveyorMiddle = QPushButton(self.layoutWidget_6)
        self.bIWrappingConveyorMiddle.setObjectName(u"bIWrappingConveyorMiddle")
        self.bIWrappingConveyorMiddle.setIcon(icon)
        self.bIWrappingConveyorMiddle.setIconSize(QSize(20, 20))
        self.bIWrappingConveyorMiddle.setFlat(True)

        self.horizontalLayout_6.addWidget(self.bIWrappingConveyorMiddle)

        self.bIWrappingConveyorEnd = QPushButton(self.layoutWidget_6)
        self.bIWrappingConveyorEnd.setObjectName(u"bIWrappingConveyorEnd")
        self.bIWrappingConveyorEnd.setIcon(icon)
        self.bIWrappingConveyorEnd.setIconSize(QSize(20, 20))
        self.bIWrappingConveyorEnd.setFlat(True)

        self.horizontalLayout_6.addWidget(self.bIWrappingConveyorEnd)

        self.bIWrappingConveyorExit = QPushButton(self.layoutWidget_6)
        self.bIWrappingConveyorExit.setObjectName(u"bIWrappingConveyorExit")
        self.bIWrappingConveyorExit.setIcon(icon)
        self.bIWrappingConveyorExit.setIconSize(QSize(20, 20))
        self.bIWrappingConveyorExit.setFlat(True)

        self.horizontalLayout_6.addWidget(self.bIWrappingConveyorExit)

        self.layoutWidget_7 = QWidget(self.frame)
        self.layoutWidget_7.setObjectName(u"layoutWidget_7")
        self.layoutWidget_7.setGeometry(QRect(1364, 197, 260, 28))
        self.horizontalLayout_7 = QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_7.setSpacing(35)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.bIExitConveyorHome = QPushButton(self.layoutWidget_7)
        self.bIExitConveyorHome.setObjectName(u"bIExitConveyorHome")
        self.bIExitConveyorHome.setIcon(icon)
        self.bIExitConveyorHome.setIconSize(QSize(20, 20))
        self.bIExitConveyorHome.setFlat(True)

        self.horizontalLayout_7.addWidget(self.bIExitConveyorHome)

        self.bIExitConveyorMiddle = QPushButton(self.layoutWidget_7)
        self.bIExitConveyorMiddle.setObjectName(u"bIExitConveyorMiddle")
        self.bIExitConveyorMiddle.setIcon(icon)
        self.bIExitConveyorMiddle.setIconSize(QSize(20, 20))
        self.bIExitConveyorMiddle.setFlat(True)

        self.horizontalLayout_7.addWidget(self.bIExitConveyorMiddle)

        self.bIExitConveyorEnd = QPushButton(self.layoutWidget_7)
        self.bIExitConveyorEnd.setObjectName(u"bIExitConveyorEnd")
        self.bIExitConveyorEnd.setIcon(icon)
        self.bIExitConveyorEnd.setIconSize(QSize(20, 20))
        self.bIExitConveyorEnd.setFlat(True)

        self.horizontalLayout_7.addWidget(self.bIExitConveyorEnd)

        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 5)
        self.bIExitConveyorExit = QPushButton(self.frame)
        self.bIExitConveyorExit.setObjectName(u"bIExitConveyorExit")
        self.bIExitConveyorExit.setGeometry(QRect(1705, 214, 35, 28))
        self.bIExitConveyorExit.setIcon(icon)
        self.bIExitConveyorExit.setIconSize(QSize(20, 20))
        self.bIExitConveyorExit.setFlat(True)
        self.bIConeOrientationTopLimitSwitch = QPushButton(self.frame)
        self.bIConeOrientationTopLimitSwitch.setObjectName(u"bIConeOrientationTopLimitSwitch")
        self.bIConeOrientationTopLimitSwitch.setGeometry(QRect(776, 143, 35, 28))
        self.bIConeOrientationTopLimitSwitch.setIcon(icon)
        self.bIConeOrientationTopLimitSwitch.setIconSize(QSize(20, 20))
        self.bIConeOrientationTopLimitSwitch.setFlat(True)
        self.bISealingTopPistonEnd = QPushButton(self.frame)
        self.bISealingTopPistonEnd.setObjectName(u"bISealingTopPistonEnd")
        self.bISealingTopPistonEnd.setGeometry(QRect(1327, 379, 17, 18))
        self.bISealingTopPistonEnd.setFont(font)
        self.bISealingTopPistonEnd.setFocusPolicy(Qt.NoFocus)
        self.bISealingTopPistonEnd.setToolTipDuration(4)
        self.bISealingTopPistonEnd.setIcon(icon1)
        self.bISealingTopPistonEnd.setIconSize(QSize(100, 100))
        self.bISealingTopPistonEnd.setFlat(True)
        self.bQSealingTopPiston = QPushButton(self.frame)
        self.bQSealingTopPiston.setObjectName(u"bQSealingTopPiston")
        self.bQSealingTopPiston.setGeometry(QRect(1327, 338, 16, 41))
        self.bQSealingTopPiston.setIcon(icon2)
        self.bQSealingTopPiston.setIconSize(QSize(200, 200))
        self.bQSealingTopPiston.setAutoRepeatDelay(300)
        self.bQSealingTopPiston.setFlat(True)
        self.bISealingTopPistonHome = QPushButton(self.frame)
        self.bISealingTopPistonHome.setObjectName(u"bISealingTopPistonHome")
        self.bISealingTopPistonHome.setGeometry(QRect(1327, 319, 17, 19))
        self.bISealingTopPistonHome.setFont(font)
        self.bISealingTopPistonHome.setFocusPolicy(Qt.NoFocus)
        self.bISealingTopPistonHome.setToolTipDuration(4)
        self.bISealingTopPistonHome.setIcon(icon1)
        self.bISealingTopPistonHome.setIconSize(QSize(100, 100))
        self.bISealingTopPistonHome.setFlat(True)
        self.bISealingBottomPistonEnd = QPushButton(self.frame)
        self.bISealingBottomPistonEnd.setObjectName(u"bISealingBottomPistonEnd")
        self.bISealingBottomPistonEnd.setGeometry(QRect(1326, 471, 17, 18))
        self.bISealingBottomPistonEnd.setFont(font)
        self.bISealingBottomPistonEnd.setFocusPolicy(Qt.NoFocus)
        self.bISealingBottomPistonEnd.setToolTipDuration(4)
        self.bISealingBottomPistonEnd.setIcon(icon1)
        self.bISealingBottomPistonEnd.setIconSize(QSize(100, 100))
        self.bISealingBottomPistonEnd.setFlat(True)
        self.bQSealingBottomPiston = QPushButton(self.frame)
        self.bQSealingBottomPiston.setObjectName(u"bQSealingBottomPiston")
        self.bQSealingBottomPiston.setGeometry(QRect(1327, 429, 16, 41))
        self.bQSealingBottomPiston.setIcon(icon2)
        self.bQSealingBottomPiston.setIconSize(QSize(200, 200))
        self.bQSealingBottomPiston.setAutoRepeatDelay(300)
        self.bQSealingBottomPiston.setFlat(True)
        self.bISealingBottomPistonHome = QPushButton(self.frame)
        self.bISealingBottomPistonHome.setObjectName(u"bISealingBottomPistonHome")
        self.bISealingBottomPistonHome.setGeometry(QRect(1327, 410, 17, 19))
        self.bISealingBottomPistonHome.setFont(font)
        self.bISealingBottomPistonHome.setFocusPolicy(Qt.NoFocus)
        self.bISealingBottomPistonHome.setToolTipDuration(4)
        self.bISealingBottomPistonHome.setIcon(icon1)
        self.bISealingBottomPistonHome.setIconSize(QSize(100, 100))
        self.bISealingBottomPistonHome.setFlat(True)
        self.bIFilmTensionRodHome = QPushButton(self.frame)
        self.bIFilmTensionRodHome.setObjectName(u"bIFilmTensionRodHome")
        self.bIFilmTensionRodHome.setGeometry(QRect(1247, 279, 37, 19))
        self.bIFilmTensionRodHome.setFont(font)
        self.bIFilmTensionRodHome.setFocusPolicy(Qt.NoFocus)
        self.bIFilmTensionRodHome.setToolTipDuration(4)
        icon6 = QIcon()
        icon6.addFile(u":/buttonImage/greenButton.png", QSize(), QIcon.Normal, QIcon.Off)
        icon6.addFile(u":/buttonImage/redButton.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.bIFilmTensionRodHome.setIcon(icon6)
        self.bIFilmTensionRodHome.setIconSize(QSize(20, 20))
        self.bIFilmTensionRodHome.setFlat(True)
        self.bIFilmTensionRodEnd = QPushButton(self.frame)
        self.bIFilmTensionRodEnd.setObjectName(u"bIFilmTensionRodEnd")
        self.bIFilmTensionRodEnd.setGeometry(QRect(1296, 278, 37, 20))
        self.bIFilmTensionRodEnd.setFont(font)
        self.bIFilmTensionRodEnd.setFocusPolicy(Qt.NoFocus)
        self.bIFilmTensionRodEnd.setToolTipDuration(4)
        self.bIFilmTensionRodEnd.setIcon(icon6)
        self.bIFilmTensionRodEnd.setIconSize(QSize(20, 20))
        self.bIFilmTensionRodEnd.setFlat(True)
        self.bQFilmRollerMotor = QPushButton(self.frame)
        self.bQFilmRollerMotor.setObjectName(u"bQFilmRollerMotor")
        self.bQFilmRollerMotor.setGeometry(QRect(1243, 186, 91, 101))
        icon7 = QIcon()
        icon7.addFile(u":/wrapping/wrappingBoothOn.png", QSize(), QIcon.Normal, QIcon.Off)
        icon7.addFile(u":/wrapping/wrappingBooth.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.bQFilmRollerMotor.setIcon(icon7)
        self.bQFilmRollerMotor.setIconSize(QSize(200, 200))
        self.bQFilmRollerMotor.setFlat(True)
        self.bIExitPistonEnd = QPushButton(self.frame)
        self.bIExitPistonEnd.setObjectName(u"bIExitPistonEnd")
        self.bIExitPistonEnd.setGeometry(QRect(1706, 179, 28, 18))
        self.bIExitPistonEnd.setFont(font)
        self.bIExitPistonEnd.setFocusPolicy(Qt.NoFocus)
        self.bIExitPistonEnd.setToolTipDuration(4)
        self.bIExitPistonEnd.setIcon(icon1)
        self.bIExitPistonEnd.setIconSize(QSize(100, 100))
        self.bIExitPistonEnd.setFlat(True)
        self.bQExitPiston = QPushButton(self.frame)
        self.bQExitPiston.setObjectName(u"bQExitPiston")
        self.bQExitPiston.setGeometry(QRect(1707, 137, 26, 42))
        self.bQExitPiston.setIcon(icon2)
        self.bQExitPiston.setIconSize(QSize(200, 200))
        self.bQExitPiston.setAutoRepeatDelay(300)
        self.bQExitPiston.setFlat(True)
        self.bIExitPistonHome = QPushButton(self.frame)
        self.bIExitPistonHome.setObjectName(u"bIExitPistonHome")
        self.bIExitPistonHome.setGeometry(QRect(1706, 119, 28, 20))
        self.bIExitPistonHome.setFont(font)
        self.bIExitPistonHome.setFocusPolicy(Qt.NoFocus)
        self.bIExitPistonHome.setToolTipDuration(4)
        self.bIExitPistonHome.setIcon(icon1)
        self.bIExitPistonHome.setIconSize(QSize(100, 100))
        self.bIExitPistonHome.setFlat(True)
        self.bQCTP_ConeHolderPiston = QPushButton(self.frame)
        self.bQCTP_ConeHolderPiston.setObjectName(u"bQCTP_ConeHolderPiston")
        self.bQCTP_ConeHolderPiston.setGeometry(QRect(710, 260, 38, 14))
        self.bQCTP_ConeHolderPiston.setIcon(icon5)
        self.bQCTP_ConeHolderPiston.setIconSize(QSize(200, 200))
        self.bQCTP_ConeHolderPiston.setFlat(True)
        self.bITiltingConeHolderHome = QPushButton(self.frame)
        self.bITiltingConeHolderHome.setObjectName(u"bITiltingConeHolderHome")
        self.bITiltingConeHolderHome.setGeometry(QRect(693, 260, 17, 14))
        self.bITiltingConeHolderHome.setFont(font)
        self.bITiltingConeHolderHome.setFocusPolicy(Qt.NoFocus)
        self.bITiltingConeHolderHome.setToolTipDuration(4)
        self.bITiltingConeHolderHome.setIcon(icon1)
        self.bITiltingConeHolderHome.setIconSize(QSize(100, 100))
        self.bITiltingConeHolderHome.setFlat(True)
        self.bITiltingConeHolderEnd = QPushButton(self.frame)
        self.bITiltingConeHolderEnd.setObjectName(u"bITiltingConeHolderEnd")
        self.bITiltingConeHolderEnd.setGeometry(QRect(749, 260, 16, 13))
        self.bITiltingConeHolderEnd.setFont(font)
        self.bITiltingConeHolderEnd.setFocusPolicy(Qt.NoFocus)
        self.bITiltingConeHolderEnd.setToolTipDuration(4)
        self.bITiltingConeHolderEnd.setIcon(icon1)
        self.bITiltingConeHolderEnd.setIconSize(QSize(100, 100))
        self.bITiltingConeHolderEnd.setFlat(True)
        self.bASealingTrigged_1 = QPushButton(self.frame)
        self.bASealingTrigged_1.setObjectName(u"bASealingTrigged_1")
        self.bASealingTrigged_1.setGeometry(QRect(1326, 197, 17, 76))
        self.bASealingTrigged_1.setIcon(icon2)
        self.bASealingTrigged_1.setIconSize(QSize(200, 200))
        self.bASealingTrigged_1.setAutoRepeatDelay(300)
        self.bASealingTrigged_1.setFlat(True)
        self.bASealingTrigged_2 = QPushButton(self.frame)
        self.bASealingTrigged_2.setObjectName(u"bASealingTrigged_2")
        self.bASealingTrigged_2.setGeometry(QRect(1301, 399, 68, 10))
        self.bASealingTrigged_2.setIcon(icon2)
        self.bASealingTrigged_2.setIconSize(QSize(200, 200))
        self.bASealingTrigged_2.setAutoRepeatDelay(300)
        self.bASealingTrigged_2.setFlat(True)
        self.label_group = QGroupBox(self.frame)
        self.label_group.setObjectName(u"label_group")
        self.label_group.setGeometry(QRect(1730, 540, 151, 144))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_group.setFont(font1)
        self.label_group.setStyleSheet(u"QGroupBox#label_group{background-color: rgb(255, 255, 255);border-radius: 10px;spacing: 10}")
        self.label_group.setAlignment(Qt.AlignCenter)
        self.gridLayout_2 = QGridLayout(self.label_group)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.pushButton_14 = QPushButton(self.label_group)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setFont(font)
        self.pushButton_14.setFocusPolicy(Qt.NoFocus)
        self.pushButton_14.setToolTipDuration(4)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QSize(20, 20))
        self.pushButton_14.setFlat(True)

        self.verticalLayout.addWidget(self.pushButton_14)

        self.pushButton_19 = QPushButton(self.label_group)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setFont(font)
        self.pushButton_19.setFocusPolicy(Qt.NoFocus)
        self.pushButton_19.setToolTipDuration(4)
        self.pushButton_19.setIcon(icon1)
        self.pushButton_19.setIconSize(QSize(20, 20))
        self.pushButton_19.setFlat(True)

        self.verticalLayout.addWidget(self.pushButton_19)

        self.pushButton_15 = QPushButton(self.label_group)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setFont(font)
        self.pushButton_15.setFocusPolicy(Qt.NoFocus)
        self.pushButton_15.setToolTipDuration(4)
        self.pushButton_15.setIcon(icon4)
        self.pushButton_15.setIconSize(QSize(20, 20))
        self.pushButton_15.setFlat(True)

        self.verticalLayout.addWidget(self.pushButton_15)

        self.pushButton_20 = QPushButton(self.label_group)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setFont(font)
        self.pushButton_20.setFocusPolicy(Qt.NoFocus)
        self.pushButton_20.setToolTipDuration(4)
        icon8 = QIcon()
        icon8.addFile(u":/magneticSwitch/greenSquareButton.png", QSize(), QIcon.Normal, QIcon.Off)
        icon8.addFile(u":/magneticSwitch/greenSquareButton.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.pushButton_20.setIcon(icon8)
        self.pushButton_20.setIconSize(QSize(20, 20))
        self.pushButton_20.setFlat(True)

        self.verticalLayout.addWidget(self.pushButton_20)

        self.pushButton_21 = QPushButton(self.label_group)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setFont(font)
        self.pushButton_21.setFocusPolicy(Qt.NoFocus)
        self.pushButton_21.setToolTipDuration(4)
        icon9 = QIcon()
        icon9.addFile(u":/magneticSwitch/redSquareButton.png", QSize(), QIcon.Normal, QIcon.Off)
        icon9.addFile(u":/magneticSwitch/redSquareButton.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.pushButton_21.setIcon(icon9)
        self.pushButton_21.setIconSize(QSize(20, 20))
        self.pushButton_21.setFlat(True)

        self.verticalLayout.addWidget(self.pushButton_21)


        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.Input_group = QGroupBox(self.frame)
        self.Input_group.setObjectName(u"Input_group")
        self.Input_group.setGeometry(QRect(1600, 320, 282, 208))
        self.Input_group.setFont(font1)
        self.Input_group.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.Input_group.setAlignment(Qt.AlignCenter)
        self.gridLayout_3 = QGridLayout(self.Input_group)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.bIRetA_StartPB = QPushButton(self.Input_group)
        self.bIRetA_StartPB.setObjectName(u"bIRetA_StartPB")
        self.bIRetA_StartPB.setMinimumSize(QSize(20, 20))
        self.bIRetA_StartPB.setMaximumSize(QSize(20, 20))
        self.bIRetA_StartPB.setFont(font)
        self.bIRetA_StartPB.setFocusPolicy(Qt.NoFocus)
        self.bIRetA_StartPB.setToolTipDuration(4)
        self.bIRetA_StartPB.setIcon(icon)
        self.bIRetA_StartPB.setIconSize(QSize(20, 20))
        self.bIRetA_StartPB.setFlat(True)

        self.horizontalLayout_11.addWidget(self.bIRetA_StartPB)

        self.bIRetA_StartPB_Label = QLabel(self.Input_group)
        self.bIRetA_StartPB_Label.setObjectName(u"bIRetA_StartPB_Label")
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setBold(True)
        font2.setWeight(75)
        self.bIRetA_StartPB_Label.setFont(font2)
        self.bIRetA_StartPB_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_11.addWidget(self.bIRetA_StartPB_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_11, 5, 0, 1, 1)

        self.horizontalLayout_14 = QHBoxLayout()
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.bIStopPB = QPushButton(self.Input_group)
        self.bIStopPB.setObjectName(u"bIStopPB")
        self.bIStopPB.setMinimumSize(QSize(20, 20))
        self.bIStopPB.setMaximumSize(QSize(20, 20))
        self.bIStopPB.setFont(font)
        self.bIStopPB.setFocusPolicy(Qt.NoFocus)
        self.bIStopPB.setToolTipDuration(4)
        self.bIStopPB.setIcon(icon)
        self.bIStopPB.setIconSize(QSize(20, 20))
        self.bIStopPB.setFlat(True)

        self.horizontalLayout_14.addWidget(self.bIStopPB)

        self.bIStopPB_Label = QLabel(self.Input_group)
        self.bIStopPB_Label.setObjectName(u"bIStopPB_Label")
        self.bIStopPB_Label.setFont(font2)
        self.bIStopPB_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_14.addWidget(self.bIStopPB_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_14, 1, 1, 1, 1)

        self.horizontalLayout_16 = QHBoxLayout()
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.bIStartPB = QPushButton(self.Input_group)
        self.bIStartPB.setObjectName(u"bIStartPB")
        self.bIStartPB.setMinimumSize(QSize(20, 20))
        self.bIStartPB.setMaximumSize(QSize(20, 20))
        self.bIStartPB.setFont(font)
        self.bIStartPB.setFocusPolicy(Qt.NoFocus)
        self.bIStartPB.setToolTipDuration(4)
        self.bIStartPB.setIcon(icon)
        self.bIStartPB.setIconSize(QSize(20, 20))
        self.bIStartPB.setFlat(True)

        self.horizontalLayout_16.addWidget(self.bIStartPB)

        self.bIStartPB_Label = QLabel(self.Input_group)
        self.bIStartPB_Label.setObjectName(u"bIStartPB_Label")
        self.bIStartPB_Label.setFont(font2)
        self.bIStartPB_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_16.addWidget(self.bIStartPB_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.bIEmergencyPB = QPushButton(self.Input_group)
        self.bIEmergencyPB.setObjectName(u"bIEmergencyPB")
        self.bIEmergencyPB.setMinimumSize(QSize(20, 20))
        self.bIEmergencyPB.setMaximumSize(QSize(20, 20))
        self.bIEmergencyPB.setFont(font)
        self.bIEmergencyPB.setFocusPolicy(Qt.NoFocus)
        self.bIEmergencyPB.setToolTipDuration(4)
        self.bIEmergencyPB.setIcon(icon)
        self.bIEmergencyPB.setIconSize(QSize(20, 20))
        self.bIEmergencyPB.setFlat(True)

        self.horizontalLayout_8.addWidget(self.bIEmergencyPB)

        self.bIEmergencyPB_Label = QLabel(self.Input_group)
        self.bIEmergencyPB_Label.setObjectName(u"bIEmergencyPB_Label")
        font3 = QFont()
        font3.setBold(True)
        font3.setWeight(75)
        self.bIEmergencyPB_Label.setFont(font3)
        self.bIEmergencyPB_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_8.addWidget(self.bIEmergencyPB_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)

        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.bIProgramKeySwitch = QPushButton(self.Input_group)
        self.bIProgramKeySwitch.setObjectName(u"bIProgramKeySwitch")
        self.bIProgramKeySwitch.setMinimumSize(QSize(20, 20))
        self.bIProgramKeySwitch.setMaximumSize(QSize(20, 20))
        self.bIProgramKeySwitch.setFont(font)
        self.bIProgramKeySwitch.setFocusPolicy(Qt.NoFocus)
        self.bIProgramKeySwitch.setToolTipDuration(4)
        self.bIProgramKeySwitch.setIcon(icon)
        self.bIProgramKeySwitch.setIconSize(QSize(20, 20))
        self.bIProgramKeySwitch.setFlat(True)

        self.horizontalLayout_10.addWidget(self.bIProgramKeySwitch)

        self.bIProgramKeySwitch_Label = QLabel(self.Input_group)
        self.bIProgramKeySwitch_Label.setObjectName(u"bIProgramKeySwitch_Label")
        self.bIProgramKeySwitch_Label.setFont(font2)
        self.bIProgramKeySwitch_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_10.addWidget(self.bIProgramKeySwitch_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_10, 3, 1, 1, 1)

        self.horizontalLayout_20 = QHBoxLayout()
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.bIResetPB = QPushButton(self.Input_group)
        self.bIResetPB.setObjectName(u"bIResetPB")
        self.bIResetPB.setMinimumSize(QSize(20, 20))
        self.bIResetPB.setMaximumSize(QSize(20, 20))
        self.bIResetPB.setFont(font)
        self.bIResetPB.setFocusPolicy(Qt.NoFocus)
        self.bIResetPB.setToolTipDuration(4)
        self.bIResetPB.setIcon(icon)
        self.bIResetPB.setIconSize(QSize(20, 20))
        self.bIResetPB.setFlat(True)

        self.horizontalLayout_20.addWidget(self.bIResetPB)

        self.bIResetPB_Label = QLabel(self.Input_group)
        self.bIResetPB_Label.setObjectName(u"bIResetPB_Label")
        self.bIResetPB_Label.setFont(font2)
        self.bIResetPB_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_20.addWidget(self.bIResetPB_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_20, 2, 0, 1, 1)

        self.horizontalLayout_21 = QHBoxLayout()
        self.horizontalLayout_21.setObjectName(u"horizontalLayout_21")
        self.bIPressureSwitch = QPushButton(self.Input_group)
        self.bIPressureSwitch.setObjectName(u"bIPressureSwitch")
        self.bIPressureSwitch.setMinimumSize(QSize(20, 20))
        self.bIPressureSwitch.setMaximumSize(QSize(20, 20))
        self.bIPressureSwitch.setFont(font)
        self.bIPressureSwitch.setFocusPolicy(Qt.NoFocus)
        self.bIPressureSwitch.setToolTipDuration(4)
        self.bIPressureSwitch.setIcon(icon)
        self.bIPressureSwitch.setIconSize(QSize(20, 20))
        self.bIPressureSwitch.setFlat(True)

        self.horizontalLayout_21.addWidget(self.bIPressureSwitch)

        self.bIPressureSwitch_Label = QLabel(self.Input_group)
        self.bIPressureSwitch_Label.setObjectName(u"bIPressureSwitch_Label")
        self.bIPressureSwitch_Label.setFont(font2)
        self.bIPressureSwitch_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_21.addWidget(self.bIPressureSwitch_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_21, 4, 1, 1, 1)

        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.bIAutoManualSwitch = QPushButton(self.Input_group)
        self.bIAutoManualSwitch.setObjectName(u"bIAutoManualSwitch")
        self.bIAutoManualSwitch.setMinimumSize(QSize(20, 20))
        self.bIAutoManualSwitch.setMaximumSize(QSize(20, 20))
        self.bIAutoManualSwitch.setFont(font)
        self.bIAutoManualSwitch.setFocusPolicy(Qt.NoFocus)
        self.bIAutoManualSwitch.setToolTipDuration(4)
        self.bIAutoManualSwitch.setIcon(icon)
        self.bIAutoManualSwitch.setIconSize(QSize(20, 20))
        self.bIAutoManualSwitch.setFlat(True)

        self.horizontalLayout_9.addWidget(self.bIAutoManualSwitch)

        self.bIAutoManualSwitch_Label = QLabel(self.Input_group)
        self.bIAutoManualSwitch_Label.setObjectName(u"bIAutoManualSwitch_Label")
        self.bIAutoManualSwitch_Label.setFont(font2)
        self.bIAutoManualSwitch_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_9.addWidget(self.bIAutoManualSwitch_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)

        self.horizontalLayout_18 = QHBoxLayout()
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.bIPausePB = QPushButton(self.Input_group)
        self.bIPausePB.setObjectName(u"bIPausePB")
        self.bIPausePB.setMinimumSize(QSize(20, 20))
        self.bIPausePB.setMaximumSize(QSize(20, 20))
        self.bIPausePB.setFont(font)
        self.bIPausePB.setFocusPolicy(Qt.NoFocus)
        self.bIPausePB.setToolTipDuration(4)
        self.bIPausePB.setIcon(icon)
        self.bIPausePB.setIconSize(QSize(20, 20))
        self.bIPausePB.setFlat(True)

        self.horizontalLayout_18.addWidget(self.bIPausePB)

        self.bIPausePB_Label = QLabel(self.Input_group)
        self.bIPausePB_Label.setObjectName(u"bIPausePB_Label")
        self.bIPausePB_Label.setFont(font2)
        self.bIPausePB_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_18.addWidget(self.bIPausePB_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_18, 4, 0, 1, 1)

        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.bIRetB_StartPB = QPushButton(self.Input_group)
        self.bIRetB_StartPB.setObjectName(u"bIRetB_StartPB")
        self.bIRetB_StartPB.setMinimumSize(QSize(20, 20))
        self.bIRetB_StartPB.setMaximumSize(QSize(20, 20))
        self.bIRetB_StartPB.setFont(font)
        self.bIRetB_StartPB.setFocusPolicy(Qt.NoFocus)
        self.bIRetB_StartPB.setToolTipDuration(4)
        self.bIRetB_StartPB.setIcon(icon)
        self.bIRetB_StartPB.setIconSize(QSize(20, 20))
        self.bIRetB_StartPB.setFlat(True)

        self.horizontalLayout_12.addWidget(self.bIRetB_StartPB)

        self.bIRetB_StartPB_Label = QLabel(self.Input_group)
        self.bIRetB_StartPB_Label.setObjectName(u"bIRetB_StartPB_Label")
        self.bIRetB_StartPB_Label.setFont(font2)
        self.bIRetB_StartPB_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_12.addWidget(self.bIRetB_StartPB_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_12, 5, 1, 1, 1)

        self.horizontalLayout_17 = QHBoxLayout()
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.bIManualSealingPB = QPushButton(self.Input_group)
        self.bIManualSealingPB.setObjectName(u"bIManualSealingPB")
        self.bIManualSealingPB.setMinimumSize(QSize(20, 20))
        self.bIManualSealingPB.setMaximumSize(QSize(20, 20))
        self.bIManualSealingPB.setFont(font)
        self.bIManualSealingPB.setFocusPolicy(Qt.NoFocus)
        self.bIManualSealingPB.setToolTipDuration(4)
        self.bIManualSealingPB.setIcon(icon)
        self.bIManualSealingPB.setIconSize(QSize(20, 20))
        self.bIManualSealingPB.setFlat(True)

        self.horizontalLayout_17.addWidget(self.bIManualSealingPB)

        self.bIManualSealingPB_Label = QLabel(self.Input_group)
        self.bIManualSealingPB_Label.setObjectName(u"bIManualSealingPB_Label")
        self.bIManualSealingPB_Label.setFont(font2)
        self.bIManualSealingPB_Label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_17.addWidget(self.bIManualSealingPB_Label)


        self.gridLayout_3.addLayout(self.horizontalLayout_17, 6, 0, 1, 1)

        self.ProductionStatus = QGroupBox(self.frame)
        self.ProductionStatus.setObjectName(u"ProductionStatus")
        self.ProductionStatus.setGeometry(QRect(100, 510, 591, 301))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.ProductionStatus.setFont(font4)
        self.ProductionStatus.setStyleSheet(u"QGroupBox{background-color: rgb(255, 255, 255);border-radius: 10px;spacing: 10}\n"
"QGroupBox::title {  subcontrol-origin:  margin;   subcontrol-position: top center;padding: 0 10px 20px 10px ;}")
        self.ProductionStatus.setAlignment(Qt.AlignCenter)
        self.gridLayout_5 = QGridLayout(self.ProductionStatus)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(-1, 15, -1, -1)
        self.tableWidget = QTableWidget(self.ProductionStatus)
        if (self.tableWidget.columnCount() < 3):
            self.tableWidget.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setFont(font3);
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setFont(font3);
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setFont(font3);
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        if (self.tableWidget.rowCount() < 5):
            self.tableWidget.setRowCount(5)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, __qtablewidgetitem7)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setFont(font3)
        self.tableWidget.setFrameShape(QFrame.StyledPanel)
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setTextElideMode(Qt.ElideRight)
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(80)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(145)

        self.gridLayout_5.addWidget(self.tableWidget, 0, 0, 1, 1)

        self.bISealingSensor = QPushButton(self.frame)
        self.bISealingSensor.setObjectName(u"bISealingSensor")
        self.bISealingSensor.setGeometry(QRect(1310, 170, 37, 20))
        self.bISealingSensor.setFont(font)
        self.bISealingSensor.setFocusPolicy(Qt.NoFocus)
        self.bISealingSensor.setToolTipDuration(4)
        self.bISealingSensor.setIcon(icon6)
        self.bISealingSensor.setIconSize(QSize(20, 20))
        self.bISealingSensor.setFlat(True)
        self.bQTransferConveyorMotor = QPushButton(self.frame)
        self.bQTransferConveyorMotor.setObjectName(u"bQTransferConveyorMotor")
        self.bQTransferConveyorMotor.setGeometry(QRect(810, 198, 21, 78))
        self.bQTransferConveyorMotor.setFont(font)
        self.bQTransferConveyorMotor.setFocusPolicy(Qt.NoFocus)
        self.bQTransferConveyorMotor.setToolTipDuration(4)
        self.bQTransferConveyorMotor.setIcon(icon4)
        self.bQTransferConveyorMotor.setIconSize(QSize(100, 100))
        self.bQTransferConveyorMotor.setFlat(True)
        self.bQWrappingConveyorMotor = QPushButton(self.frame)
        self.bQWrappingConveyorMotor.setObjectName(u"bQWrappingConveyorMotor")
        self.bQWrappingConveyorMotor.setGeometry(QRect(1069, 196, 21, 78))
        self.bQWrappingConveyorMotor.setFont(font)
        self.bQWrappingConveyorMotor.setFocusPolicy(Qt.NoFocus)
        self.bQWrappingConveyorMotor.setToolTipDuration(4)
        self.bQWrappingConveyorMotor.setIcon(icon4)
        self.bQWrappingConveyorMotor.setIconSize(QSize(100, 100))
        self.bQWrappingConveyorMotor.setFlat(True)
        self.bQExitConveyorMotor = QPushButton(self.frame)
        self.bQExitConveyorMotor.setObjectName(u"bQExitConveyorMotor")
        self.bQExitConveyorMotor.setGeometry(QRect(1343, 196, 21, 78))
        self.bQExitConveyorMotor.setFont(font)
        self.bQExitConveyorMotor.setFocusPolicy(Qt.NoFocus)
        self.bQExitConveyorMotor.setToolTipDuration(4)
        self.bQExitConveyorMotor.setIcon(icon4)
        self.bQExitConveyorMotor.setIconSize(QSize(100, 100))
        self.bQExitConveyorMotor.setFlat(True)

        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1544, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.bICFCConeStopSensor.setText("")
        self.bIRetA_Middle.setText("")
        self.bQRetB_WeightOk.setText("")
        self.bIRetB_End.setText("")
        self.bQConeFeedingPiston.setText("")
        self.bIRetB_ConeDetection1.setText("")
        self.bIRetB_ConeDetection2.setText("")
        self.bIRetB_ConeDetection3.setText("")
        self.bIRetB_ConeDetection4.setText("")
        self.bQRetAForward.setText("")
        self.bQFeedingConveyorMotor.setText("")
        self.bIRetA_ConeDetection1.setText("")
        self.bIRetA_ConeDetection2.setText("")
        self.bIRetA_ConeDetection3.setText("")
        self.bIRetA_ConeDetection4.setText("")
        self.bIRetA_Home.setText("")
        self.bQRetBForward.setText("")
        self.bQRetA_WeightOk.setText("")
        self.bIConeFeedingPistonEnd.setText("")
        self.bIRetA_End.setText("")
        self.bIRetA_ConeCrossLimitSwitch.setText("")
        self.bIRetB_Middle.setText("")
        self.bIRetB_ConeCrossLimitSwitch.setText("")
        self.Ret_A_Wt.setText("")
        self.Ret_B_Wt.setText("")
        self.bIConeFeedingPistonHome.setText("")
        self.bIRetB_Home.setText("")
        self.bIForwardPistonEnd.setText("")
        self.bIForwardPistonHome.setText("")
        self.bQForwardPiston.setText("")
        self.bIConeTiltingPistonHome.setText("")
        self.bQConeTiltingPistonForward.setText("")
        self.bIConeTiltingPistonEnd.setText("")
        self.bITransferConveyorHome.setText("")
        self.bITransferConveyorMiddle.setText("")
        self.bITransferConveyorEnd.setText("")
        self.bITransferConveyorExit.setText("")
        self.bIWrappingConveyorHome.setText("")
        self.bIWrappingConveyorMiddle.setText("")
        self.bIWrappingConveyorEnd.setText("")
        self.bIWrappingConveyorExit.setText("")
        self.bIExitConveyorHome.setText("")
        self.bIExitConveyorMiddle.setText("")
        self.bIExitConveyorEnd.setText("")
        self.bIExitConveyorExit.setText("")
        self.bIConeOrientationTopLimitSwitch.setText("")
        self.bISealingTopPistonEnd.setText("")
        self.bQSealingTopPiston.setText("")
        self.bISealingTopPistonHome.setText("")
        self.bISealingBottomPistonEnd.setText("")
        self.bQSealingBottomPiston.setText("")
        self.bISealingBottomPistonHome.setText("")
        self.bIFilmTensionRodHome.setText("")
        self.bIFilmTensionRodEnd.setText("")
        self.bQFilmRollerMotor.setText("")
        self.bIExitPistonEnd.setText("")
        self.bQExitPiston.setText("")
        self.bIExitPistonHome.setText("")
        self.bQCTP_ConeHolderPiston.setText("")
        self.bITiltingConeHolderHome.setText("")
        self.bITiltingConeHolderEnd.setText("")
        self.bASealingTrigged_1.setText("")
        self.bASealingTrigged_2.setText("")
        self.label_group.setTitle(QCoreApplication.translate("MainWindow", u"Label", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"     Object sensor", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"    Reed Switch", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"       Limit Switch", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"          ON State", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"        OFF State", None))
        self.Input_group.setTitle(QCoreApplication.translate("MainWindow", u"INPUT", None))
        self.bIRetA_StartPB.setText("")
        self.bIRetA_StartPB_Label.setText(QCoreApplication.translate("MainWindow", u"Ret A Start", None))
        self.bIStopPB.setText("")
        self.bIStopPB_Label.setText(QCoreApplication.translate("MainWindow", u"MC Stop", None))
        self.bIStartPB.setText("")
        self.bIStartPB_Label.setText(QCoreApplication.translate("MainWindow", u"MC Start", None))
        self.bIEmergencyPB.setText("")
        self.bIEmergencyPB_Label.setText(QCoreApplication.translate("MainWindow", u"Emergency", None))
        self.bIProgramKeySwitch.setText("")
        self.bIProgramKeySwitch_Label.setText(QCoreApplication.translate("MainWindow", u"Program key", None))
        self.bIResetPB.setText("")
        self.bIResetPB_Label.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.bIPressureSwitch.setText("")
        self.bIPressureSwitch_Label.setText(QCoreApplication.translate("MainWindow", u"FRL", None))
        self.bIAutoManualSwitch.setText("")
        self.bIAutoManualSwitch_Label.setText(QCoreApplication.translate("MainWindow", u"Auto/Manual", None))
        self.bIPausePB.setText("")
        self.bIPausePB_Label.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.bIRetB_StartPB.setText("")
        self.bIRetB_StartPB_Label.setText(QCoreApplication.translate("MainWindow", u"Ret B Start", None))
        self.bIManualSealingPB.setText("")
        self.bIManualSealingPB_Label.setText(QCoreApplication.translate("MainWindow", u"Manual Sealing", None))
        self.ProductionStatus.setTitle(QCoreApplication.translate("MainWindow", u"Status", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"SHIFT X", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"SHIFT Y", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"SHIFT Z", None));
        ___qtablewidgetitem3 = self.tableWidget.verticalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"No Of Bags", None));
        ___qtablewidgetitem4 = self.tableWidget.verticalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Count 1", None));
        ___qtablewidgetitem5 = self.tableWidget.verticalHeaderItem(2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Count 2", None));
        ___qtablewidgetitem6 = self.tableWidget.verticalHeaderItem(3)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Production %", None));
        ___qtablewidgetitem7 = self.tableWidget.verticalHeaderItem(4)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Hourly Avarage ", None));
        self.bISealingSensor.setText("")
        self.bQTransferConveyorMotor.setText("")
        self.bQWrappingConveyorMotor.setText("")
        self.bQExitConveyorMotor.setText("")
    # retranslateUi

